dist: xenial
language: java
jdk:
- openjdk8
- openjdk11
script:
- mvn -B -Prun-itests clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
after_success:
- mvn site
- mvn site:stage
addons:
  sonarcloud:
    organization: "etourdot-github"
    token:
      secure: "$SONAR_TOKEN"
    branches:
      - develop
deploy:
  provider: pages
  local-dir: "./target/staging/"
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: develop