language: java
jdk:
- openjdk8
script:
- mvn -B -Prun-itests verify
after_success:
- mvn site
- mvn site:stage
deploy:
  provider: pages
  local-dir: "./target/staging/"
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: develop