dist: xenial
language: java

jobs:
  include:
  - stage: test jdk11
    jdk: openjdk11
    script: mvn -B -Prun-itests clean verify
  - stage: generate and deploy site
    jdk: openjdk8
    script:
    - mvn -B -Prun-itests clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
    - mvn site
    - mvn site:stage
    deploy:
      provider: pages
      local-dir: "./target/staging/"
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      on:
        branch: develop

addons:
  sonarcloud:
    organization: "etourdot-github"
    token:
      secure: "$SONAR_TOKEN"
    branches:
      - develop