language: java
jdk:
- openjdk8
after_success:
- mvn site
deploy:
  provider: pages
  local-dir: "./target/site/"
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: develop